sudo: false
language: csharp
dotnet: 1.0.0
mono:
  - latest
os:
  - linux
script: 
  - dotnet restore
  - dotnet build PromisePayDotNet
  - dotnet build PromisePayDotNet.Tests
  - cd PromisePayDotNet.Tests
  - dotnet test 
