sudo: false
language: csharp
dotnet: 1.0.1
mono:
  - latest
dist: trusty
os:
  - linux
script: 
  - dotnet restore
  - dotnet build PromisePayDotNet
  - dotnet build PromisePayDotNet.Tests
  - cd PromisePayDotNet.Tests
  - dotnet test 
