sudo: false
language: csharp
dotnet: 1.0.3
mono:
  - latest
dist: trusty
os:
  - linux
script: 
  - dotnet restore
  - dotnet build PromisePayDotNet /p:TargetFrameworkRootPath=/usr/lib/mono/xbuild-frameworks
  - dotnet build PromisePayDotNet.Tests /p:TargetFrameworkRootPath=/usr/lib/mono/xbuild-frameworks
  - cd PromisePayDotNet.Tests
  - dotnet test /p:TargetFrameworkRootPath=/usr/lib/mono/xbuild-frameworks
